param(
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\api\Data\NeetCodeCatalog.cs')
)

$ErrorActionPreference = 'Stop'

$headers = @{
    'User-Agent' = 'Modulog-Catalog-Builder'
}

$listUrl = 'https://raw.githubusercontent.com/Zanger67/WikiLeet/main/Lists/N150'
$metadataUrl = 'https://raw.githubusercontent.com/Zanger67/leetcode-question-data/main/data/leetcode_s.json'

$listText = Invoke-RestMethod -Headers $headers -Uri $listUrl
$listPattern = '(?m)^(?<number>\d+)\. (?<title>[^\r\n]+)\r?\n\r?\n(?<difficulty>Easy|Med\.|Hard)$'
$listEntries = [regex]::Matches($listText, $listPattern)

if ($listEntries.Count -ne 150) {
    throw "Expected 150 NeetCode entries but found $($listEntries.Count)."
}

$metadataResponse = Invoke-RestMethod -Headers $headers -Uri $metadataUrl
$questions = $metadataResponse.data.problemsetQuestionList.questions
$questionsByNumber = @{}

foreach ($question in $questions) {
    $questionsByNumber[[int]$question.frontendQuestionId] = $question
}

$catalog = foreach ($entry in $listEntries) {
    $number = [int]$entry.Groups['number'].Value

    if (-not $questionsByNumber.ContainsKey($number)) {
        throw "LeetCode metadata is missing problem $number."
    }

    $question = $questionsByNumber[$number]

    [pscustomobject]@{
        Number = $number
        Title = [string]$question.title
        Url = "https://leetcode.com/problems/$($question.titleSlug)/"
        Topics = @($question.topicTags | ForEach-Object { [string]$_.slug })
        Difficulty = [string]$question.difficulty
    }
}

$duplicateNumbers = $catalog | Group-Object Number | Where-Object Count -gt 1
$duplicateUrls = $catalog | Group-Object Url | Where-Object Count -gt 1

if ($duplicateNumbers -or $duplicateUrls) {
    throw 'The NeetCode catalog contains duplicate problem numbers or URLs.'
}

$difficultyCounts = $catalog | Group-Object Difficulty -AsHashTable

if ($difficultyCounts.Easy.Count -ne 28 -or
    $difficultyCounts.Medium.Count -ne 101 -or
    $difficultyCounts.Hard.Count -ne 21) {
    throw "Unexpected difficulty distribution: $(
        ($catalog | Group-Object Difficulty | ForEach-Object { "$($_.Name)=$($_.Count)" }) -join ', '
    )."
}

function ConvertTo-CSharpString {
    param([string]$Value)

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('using Modulog.Api.Domain;')
$lines.Add('')
$lines.Add('namespace Modulog.Api.Data;')
$lines.Add('')
$lines.Add('// Generated by scripts/Generate-NeetCodeCatalog.ps1. Do not edit entries manually.')
$lines.Add('internal static class NeetCodeCatalog')
$lines.Add('{')
$lines.Add('    public static readonly Problem[] Problems =')
$lines.Add('    [')

foreach ($problem in $catalog) {
    $topics = ($problem.Topics | ForEach-Object { ConvertTo-CSharpString $_ }) -join ', '
    $lines.Add('        Seed(')
    $lines.Add("            $($problem.Number),")
    $lines.Add("            $(ConvertTo-CSharpString $problem.Title),")
    $lines.Add("            $(ConvertTo-CSharpString $problem.Url),")
    $lines.Add("            [$topics],")
    $lines.Add("            Difficulty.$($problem.Difficulty)),")
}

$lines.Add('    ];')
$lines.Add('')
$lines.Add('    private static Problem Seed(')
$lines.Add('        int problemNumber,')
$lines.Add('        string title,')
$lines.Add('        string url,')
$lines.Add('        string[] topics,')
$lines.Add('        Difficulty difficulty) =>')
$lines.Add('        new()')
$lines.Add('        {')
$lines.Add('            Id = ProblemId(problemNumber),')
$lines.Add('            Title = title,')
$lines.Add('            ExternalUrl = url,')
$lines.Add('            TopicTags = topics,')
$lines.Add('            Difficulty = difficulty,')
$lines.Add('            CreatedAt = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero)')
$lines.Add('        };')
$lines.Add('')
$lines.Add('    private static Guid ProblemId(int problemNumber) =>')
$lines.Add('        problemNumber switch')
$lines.Add('        {')
$lines.Add('            // Preserve IDs from the initial migration so existing entries remain valid.')
$lines.Add('            1 => Guid.Parse("20000000-0000-0000-0000-000000000001"),')
$lines.Add('            20 => Guid.Parse("20000000-0000-0000-0000-000000000002"),')
$lines.Add('            3 => Guid.Parse("20000000-0000-0000-0000-000000000003"),')
$lines.Add('            _ => Guid.Parse($"21000000-0000-0000-0000-{problemNumber:000000000000}")')
$lines.Add('        };')
$lines.Add('}')

$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$content = [string]::Join([Environment]::NewLine, $lines) + [Environment]::NewLine
[System.IO.File]::WriteAllText(
    $resolvedOutputPath,
    $content,
    [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $($catalog.Count) catalog entries at $resolvedOutputPath."
