param(
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\api\Data\LeetCodeCatalog.cs'),
    [string]$AmazonListPath = (Join-Path $PSScriptRoot '..\catalog\amazon-last-six-months-reddit.txt')
)

$ErrorActionPreference = 'Stop'

$headers = @{
    'User-Agent' = 'Modulog-Catalog-Builder'
}

$neetcodeListUrl = 'https://raw.githubusercontent.com/Zanger67/WikiLeet/main/Lists/N150'
$metadataUrl = 'https://raw.githubusercontent.com/Zanger67/leetcode-question-data/main/data/leetcode_s.json'

$neetcodeText = Invoke-RestMethod -Headers $headers -Uri $neetcodeListUrl
$neetcodePattern = '(?m)^(?<number>\d+)\. (?<title>[^\r\n]+)\r?\n\r?\n(?<difficulty>Easy|Med\.|Hard)$'
$neetcodeEntries = [regex]::Matches($neetcodeText, $neetcodePattern)

if ($neetcodeEntries.Count -ne 150) {
    throw "Expected 150 NeetCode entries but found $($neetcodeEntries.Count)."
}

$amazonSlugs = @(
    Get-Content -LiteralPath $AmazonListPath |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -and -not $_.StartsWith('#') }
)

if ($amazonSlugs.Count -ne 95) {
    throw "Expected 95 Amazon compilation entries but found $($amazonSlugs.Count)."
}

if (($amazonSlugs | Sort-Object -Unique).Count -ne $amazonSlugs.Count) {
    throw 'The Amazon compilation manifest contains duplicate slugs.'
}

$amazonSlugSet = @{}
foreach ($slug in $amazonSlugs) {
    $amazonSlugSet[$slug] = $true
}

$metadataResponse = Invoke-RestMethod -Headers $headers -Uri $metadataUrl
$questions = $metadataResponse.data.problemsetQuestionList.questions
$questionsByNumber = @{}
$questionsBySlug = @{}

foreach ($question in $questions) {
    $number = 0

    if ([int]::TryParse([string]$question.frontendQuestionId, [ref]$number)) {
        $questionsByNumber[$number] = $question
    }

    $questionsBySlug[[string]$question.titleSlug] = $question
}

$selectedQuestions = @{}

foreach ($entry in $neetcodeEntries) {
    $number = [int]$entry.Groups['number'].Value

    if (-not $questionsByNumber.ContainsKey($number)) {
        throw "LeetCode metadata is missing problem $number."
    }

    $selectedQuestions[$number] = $questionsByNumber[$number]
}

foreach ($slug in $amazonSlugs) {
    if (-not $questionsBySlug.ContainsKey($slug)) {
        throw "LeetCode metadata is missing problem slug '$slug'."
    }

    $question = $questionsBySlug[$slug]
    $number = 0

    if (-not [int]::TryParse([string]$question.frontendQuestionId, [ref]$number)) {
        throw "Problem slug '$slug' does not have a numeric frontend identifier."
    }

    $selectedQuestions[$number] = $question
}

$catalog = @(
    $selectedQuestions.GetEnumerator() |
        ForEach-Object {
            $question = $_.Value

            [pscustomobject]@{
                Number = [int]$_.Key
                Title = [string]$question.title
                Url = "https://leetcode.com/problems/$($question.titleSlug)/"
                Topics = @($question.topicTags | ForEach-Object { [string]$_.slug })
                Companies = if ($amazonSlugSet.ContainsKey([string]$question.titleSlug)) {
                    @('Amazon')
                } else {
                    @()
                }
                Difficulty = [string]$question.difficulty
            }
        } |
        Sort-Object Number
)

if ($catalog.Count -ne 212) {
    throw "Expected 212 combined catalog entries after deduplication but found $($catalog.Count)."
}

$duplicateNumbers = $catalog | Group-Object Number | Where-Object Count -gt 1
$duplicateUrls = $catalog | Group-Object Url | Where-Object Count -gt 1

if ($duplicateNumbers -or $duplicateUrls) {
    throw 'The combined catalog contains duplicate problem numbers or URLs.'
}

function ConvertTo-CSharpString {
    param([string]$Value)

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('using Modulog.Api.Domain;')
$lines.Add('')
$lines.Add('namespace Modulog.Api.Data;')
$lines.Add('')
$lines.Add('// Generated by scripts/Generate-LeetCodeCatalog.ps1. Do not edit entries manually.')
$lines.Add('internal static class LeetCodeCatalog')
$lines.Add('{')
$lines.Add('    public static readonly Problem[] Problems =')
$lines.Add('    [')

foreach ($problem in $catalog) {
    $topics = ($problem.Topics | ForEach-Object { ConvertTo-CSharpString $_ }) -join ', '
    $companies = ($problem.Companies | ForEach-Object { ConvertTo-CSharpString $_ }) -join ', '
    $lines.Add('        Seed(')
    $lines.Add("            $($problem.Number),")
    $lines.Add("            $(ConvertTo-CSharpString $problem.Title),")
    $lines.Add("            $(ConvertTo-CSharpString $problem.Url),")
    $lines.Add("            [$topics],")
    $lines.Add("            [$companies],")
    $lines.Add("            Difficulty.$($problem.Difficulty)),")
}

$lines.Add('    ];')
$lines.Add('')
$lines.Add('    private static Problem Seed(')
$lines.Add('        int problemNumber,')
$lines.Add('        string title,')
$lines.Add('        string url,')
$lines.Add('        string[] topics,')
$lines.Add('        string[] companies,')
$lines.Add('        Difficulty difficulty) =>')
$lines.Add('        new()')
$lines.Add('        {')
$lines.Add('            Id = ProblemId(problemNumber),')
$lines.Add('            Title = title,')
$lines.Add('            ExternalUrl = url,')
$lines.Add('            TopicTags = topics,')
$lines.Add('            Companies = companies,')
$lines.Add('            Difficulty = difficulty,')
$lines.Add('            CreatedAt = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero)')
$lines.Add('        };')
$lines.Add('')
$lines.Add('    private static Guid ProblemId(int problemNumber) =>')
$lines.Add('        problemNumber switch')
$lines.Add('        {')
$lines.Add('            // Preserve IDs from the initial migration so existing entries remain valid.')
$lines.Add('            1 => Guid.Parse("20000000-0000-0000-0000-000000000001"),')
$lines.Add('            20 => Guid.Parse("20000000-0000-0000-0000-000000000002"),')
$lines.Add('            3 => Guid.Parse("20000000-0000-0000-0000-000000000003"),')
$lines.Add('            _ => Guid.Parse($"21000000-0000-0000-0000-{problemNumber:000000000000}")')
$lines.Add('        };')
$lines.Add('}')

$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$content = [string]::Join([Environment]::NewLine, $lines) + [Environment]::NewLine
[System.IO.File]::WriteAllText(
    $resolvedOutputPath,
    $content,
    [System.Text.UTF8Encoding]::new($false))

Write-Output "Generated $($catalog.Count) unique catalog entries at $resolvedOutputPath."
